import Head from "next/head";
import Layout from "@/components/layout";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Cover from "@/components/cover";
export default function Archive() {
  return (
    <>
      <Layout>
        <Head>
          <title>文章归档</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Cover />
        <Footer />
      </Layout>
    </>
  );
}
