import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/layout";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Cover from "@/components/cover";
import List from "@/components/lists";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "animate.css";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const bg = "@/assets/imgs/cover-bg.webp";
  return (
    <>
      <Layout>
        <Head>
          <title>橙子</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          {/* <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
            rel="stylesheet"
          /> */}
        </Head>
        {/* 头部 */}
        <Header />
        {/* 主体 */}
        {/* <div className="pb-8 text-gray-900 transition-all main-container bg-gray-50 dark:bg-gray-900 dark:text-white"> */}
        <Cover bg={bg} />
        <List />
        {/* </div> */}
        <Footer />
      </Layout>
    </>
  );
}
